### ISSUE TITLE
Maven equivalent of SBT's routesImport

### ISSUE THREAD

**Issue by marccarre** [play2-maven-plugin/play2-maven-plugin#108]
Hi,

First and foremost, thank you very much for maintaining the `play2-maven-plugin`, it is a very useful piece of software!

I would have a question regarding custom types in routes, for which you typically need to implement some `implicits` binders extending `PathBindable[T]` and `QueryStringBindable[T]`.
In SBT, you can specify paths to your extensions for such binders like:

    routesImport += "models.Binders._"

Is there an equivalent in the Play2 Maven plugin? 
And if not, would you know an alternative or would you have pointers to implement it?

Not having this leads to various compilation errors in the `compile` phase, as Play cannot find the binders for the routers created during the `default-routes-compile` goal.

Thanks,
M.

**Comment by gslowikowski** [comment]
Check [this commit](https://github.com/play2-maven-plugin/play2-maven-plugin/commit/1a95a066d821e5c222b4ac9c547a15592333c672) in [branch routes-import](https://github.com/play2-maven-plugin/play2-maven-plugin/tree/routes-import).

Is it what you need? `routesImport` parameter here does not specify additional  imports to default ones (as when you use `+=` or `++=` in SBT), but all imports (equivalent to using `:=` in SBT), so you have to specify the default ones too.

They are:

for Play! Framework 2.3+:
- `controllers.Assets.Asset` for Scala
- `controllers.Assets.Asset play.libs.F` for Java

for Play! Framework 2.1 and 2.2:
- nothing for Scala
- `play.libs.F` for Java

**Comment by marccarre** [comment]
Hi Grzegorz,

Yes, this commit looks exactly like what I'd need -- thank you very much for the quick turnaround!
Do you plan to merge/release it soon?

In the meantime, would you know if there is a way to still have extensions picked up with older versions of the Play2 Maven plugin? (e.g. if I was to move my binders to a specific default package or so?)

Thanks,
M.

**Comment by gslowikowski** [comment]
I'm finishing `play:run` in development mode with hot reload. It will take some more time, but I can add routes imports and publish snapshot in the meantime.

Look at Scala files generated from `routes` file. I don't see any workaround (maybe besides adding your classes to one of imported play's packages).

**Comment by gslowikowski** [comment]
I will implement it differently. `routesAdditionalImports` configuration parameter will be added. It will contain only additional imports, they will be added to default imports (not replace them).

**Comment by gslowikowski** [comment]
New `1.0.0-beta6-SNAPSHOT` snapshot deployed. Site updated.

**Comment by wanyunyang** [comment]
Hi Grzegorz,

Could you please create a release for this snapshot version as we can't use it if it is a SNAPSHOT due to some company internal constrains?

Thank you very much!
Wanyun
