### ISSUE TITLE
Compiling play dependencies with maven plugin

### ISSUE THREAD

**Issue by akmorrow13** [play2-maven-plugin/play2-maven-plugin#129]
I cannot find a way to locate local jars specified in a conf/dependencies.yml folder. Using sbt, you can run 'play dependencies' to do locate these jars. Is there a way to do this with the play2-maven-plugin?

**Comment by gslowikowski** [comment]
`conf/dependencies.yml` file is specific to Play! Framework 1.x.

In Play! Framework 2.x SBT you have to use [SBT dependency graph plugin](https://github.com/jrudolph/sbt-dependency-graph)

In Maven you have [Maven Dependency Plugin](https://maven.apache.org/plugins/maven-dependency-plugin/index.html) and it's [dependency:tree](https://maven.apache.org/plugins/maven-dependency-plugin/tree-mojo.html) goal.

If you have more questions, use Gitter, please.
