### ISSUE TITLE
Play 2.5.14 Twirl 1.2.0

### ISSUE THREAD

**Issue by yasargil** [play2-maven-plugin/play2-maven-plugin#141]
With play 2.5.14 and Twirl 1.2.0 it is possible to do injection into templates. 
I tried to override the dependency of the plugin with:

```
<dependency>
   <groupId>com.typesafe.play</groupId>
   <artifactId>twirl-compiler_2.10</artifactId>
   <version>1.2.0</version>
</dependency>
```

But it fails with an api incompatibility. Do you see a way how we can override the Play25TemplateCompiler?

**Comment by gslowikowski** [comment]
In order to support multiple Play! versions plugin delegates actual logic to providers. You have to override dependency of a provider, not a plugin.

To do this, you have to declare provider as plugin's dependency to disable auto-discovery functionality (as described in `Provider as plugin dependency` paragraph in [this documentation page](http://play2-maven-plugin.github.io/play2-maven-plugin/1.0.0-beta8/play2-providers/play2-provider-play25/usage.html) and override Twirl Compiler dependency the way you did before:

```
            <plugin>
                <groupId>com.google.code.play2-maven-plugin</groupId>
                <artifactId>play2-maven-plugin</artifactId>
                <version>1.0.0-beta8</version>
                <extensions>true</extensions>
                <dependencies>
                    <dependency>
                        <groupId>com.google.code.play2-maven-plugin</groupId>
                        <artifactId>play2-provider-play25</artifactId>
                        <version>1.0.0-beta8</version>
                    </dependency>
                    <dependency>
                        <groupId>com.typesafe.play</groupId>
                        <artifactId>twirl-compiler_2.10</artifactId>
                        <version>1.2.0</version>
                    </dependency>
                </dependencies>
            </plugin>
```

I personally never tried to override Twirl, so don't guarantee it will work.

**Comment by yasargil** [comment]
Thank you for the hint. I managed to pull if with following steps:
1. Create Plexus Component with a dependency to the play25 provider and to the twirl 1.2.0 compiler 
2. Override the getTemplatesCompiler and return the implementation of the play2.6 template compiler.
3. Add the plexus component as dependency to the play2-maven-plugin
4. Add the dependency for the twirl compiler to the project and not the plugin

Attached the plexus component could be used by others after a little modification:
[oev-play-provider.zip](https://github.com/play2-maven-plugin/play2-maven-plugin/files/1040568/oev-play-provider.zip)

**Comment by gslowikowski** [comment]
In other words, you created your custom provider. That's perfectly fine. My previous advice didn't work?

**Comment by yasargil** [comment]
I worked but the TwirlCompiler.compile api did change in 1.2.0 thats why i had to provide my own TemplateCompiler.

Thank you again.
Ticket can be closed.

**Comment by gslowikowski** [comment]
BTW, is it possible to use Twirl 1.2.0 with Play! Framework 2.5.x in SBT?

**Comment by yasargil** [comment]
Yes in the newer version of play, i think you need at least 2.5.12. 

You have to add following to make it work: 
build.sbt:
`TwirlKeys.constructorAnnotations += "@javax.inject.Inject()"`

plugins.sbt:
`addSbtPlugin("com.typesafe.sbt" % "sbt-twirl" % "1.2.0")`
