### ISSUE TITLE
Consider frontend-maven-plugin

### ISSUE THREAD

**Issue by benmccann** [play2-maven-plugin/play2-maven-plugin#144]
I see that [there's some code for Less, JavaScript, CoffeeScript, etc.](https://github.com/play2-maven-plugin/play2-maven-plugin/tree/master/play2-provider-api/src/main/java/com/google/code/play2/provider/api). Given that there's so many different frontend technologies, it seems impossible to support them all. Maybe it'd be easier to make that part pluggable and handled by other plugins.

E.g. we build Play projects with Maven in many of the Lagom examples and typically rely on [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin) for that. You can see [activator-lagom-java-chirper](https://github.com/lagom/activator-lagom-java-chirper) as an example of this. Right now it uses node directly, but I have a pull request pending to switch it to use webpack. There's webpack plugins for just about anything, so you could support all these frontend technologies without having to build anything into play2-maven-plugin for them

**Comment by gslowikowski** [comment]
The built-in assets processing tasks you mentioned are equivalent to Play!'s pre-SbtWeb tasks.

Generally, assets processing is not a part of `play2` [packaging definition](https://github.com/play2-maven-plugin/play2-maven-plugin/blob/master/play2-maven-plugin/src/main/resources/META-INF/plexus/components.xml#L43-L47). You have to add them to your project if required.

These (I call them "legacy") assets processing tasks have two advantages:
- they are fast (run inside Maven JVM, require no forking)
- exception handling in dev mode is relatively easy

An alternative solution is to use SbtWeb, but unfortunately, SbtWeb is tightly bound to SBT and cannot be used from Maven plugin. To workaround this limitation, I've created [sbtrun-maven-plugin](https://github.com/sbtrun-maven-plugin/sbtrun-maven-plugin), which forks JVM to run e.g. `web-assets:assets` task. This works, but has some disadvantages:
- requires JVM forking - slows down the build,
- requires additional (at least minimalistic) SBT build,
- exceptions cannot be processed properly in dev mode.

Compare these two sample projects:
- [Slick example using legacy tasks](https://github.com/play2-maven-plugin/play2-maven-test-projects/tree/master/play26/scala/slick-example)
- [Slick example using SbtWeb](https://github.com/play2-maven-plugin/play2-maven-test-projects/tree/master/play26/scala/slick-example-using-sbtweb)

Generally I would love to see SbtWeb refactored to decouple core functionality from SBT plugin interface (like it's done e.g. in Twirl).

For webjars we have (at least) two alternative approaches as well. Here you have a pair of test projects, using webjars:
- [ChatRoom example using webjars in runtime](https://github.com/play2-maven-plugin/play2-maven-test-projects/tree/master/play26/scala/chatroom-example-using-webjars-assets),
- [ChatRoom example unpacking assets from webjars during the build](https://github.com/play2-maven-plugin/play2-maven-test-projects/tree/master/play26/scala/chatroom-example-using-sbtweb).

[frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin) is third possible approach to assets processing. I didn't use it, so I cannot say, what are its pros and cons.

**Comment by gslowikowski** [comment]
@benmccann, didn't you consider refactoring SbtWeb plugins to separate functionality from SBT interface to allow using them in Maven and other build systems?

**Comment by gslowikowski** [comment]
I'm closing it now. Reopen if you will want to discuss it further.

**Comment by benmccann** [comment]
No, we haven't considered refactoring SbtWeb plugins to separate their functionality from SBT. I think that's unlikely to happen. I would probably suggest people to use something like Webpack instead that can be used with both Maven and SBT. I have an example of how to set that up here: https://github.com/lagom/activator-lagom-java-chirper/pull/64

**Comment by gslowikowski** [comment]
You put a lot of effort into SbtWeb implementation. Why not make it other build tools friendly?

**Comment by benmccann** [comment]
It would be a pretty significant amount of work to make corresponding Maven plugins for all the individual SBT plugins. Also, https://github.com/stonexx/sbt-webpack utilizes SbtWeb, so if people use that plugin they would still be using SbtWeb. If we use SbtWebpack then we only have to make sure that one functionality works in both SBT and Maven instead of a dozen different plugins that are barely being kept up-to-date with only an SBT version to maintain.
