### ISSUE TITLE
Not working with any version newer than 2.6.2

### ISSUE THREAD

**Issue by Paktosan** [play2-maven-plugin/play2-maven-plugin#153]
Starting with play version 2.6.3 I can no longer run the development environment. It crashes with the following log message:
`Failed to execute goal com.google.code.play2-maven-plugin:play2-maven-plugin:1.0.0-rc1:run (default-cli) on project webapp: ?: InvocationTargetException: akka/actor/ActorRefFactory: akka.actor.ActorRefFactory`

**Comment by gslowikowski** [comment]
Hi. Can you try version `1.0.0-rc2-SNAPSHOT`?
If it will fail, paste full stack trace, please.

**Comment by Paktosan** [comment]
Play! 2.6.7 is working, thanks! However I now see another issue. When I have any compile error, it should show me a error page. Instead I get a white page and this stack trace:
https://gist.github.com/Paktosan/8928bd975bd3e4e3608f37e4b9f94b31

**Comment by gslowikowski** [comment]
I didn't test is earlier. I can confirm, that something changed between version `2.6.1` and `2.6.2` of Play! (Maven plugin v. `1.0.0-rc1` works with Play! `2.6.1`, but doesn't work with `2.6.2`).

 I need more time to investigate.

**Comment by gslowikowski** [comment]
Problem fixed (see issue #158)

**Comment by gslowikowski** [comment]
Version `1.0.0-rc2` released.
