### ISSUE TITLE
Maven doesn't find play2-maven-plugin

### ISSUE THREAD

**Issue by igorek9191** [play2-maven-plugin/play2-maven-plugin#157]
Hi !
I have dowloaded Test Projects from your repository. I'm interesting in jpa-example project. Play version 2.6.7
Maven has resolved all dependencies, but about play2-maven-plugin it was print out this message:
Plugin '''com.google.code.play2-maven-plugin:play2-maven-plugin:1.0.0-rc2-SNAPSHOT''' not found
Any ideas why it is so? What I have to do? Maven version is 3.3.9

**Comment by gslowikowski** [comment]
Hi @igorek9191 

You can:
- use test project versions from [1.0.0-rc1 tag](https://github.com/play2-maven-plugin/play2-maven-test-projects/tree/test-projects-1.0.0-rc1), they use `1.0.0-rc1` version of the plugin
- configure your Maven to use snapshots repository, where version `1.0.0-rc2-SNAPSHOT` of the plugin is deployed - read **Using plugin SNAPSHOT versions** section of [documentation](https://play2-maven-plugin.github.io/play2-maven-plugin/1.0.0-rc1/usage.html)

**Comment by igorek9191** [comment]
Yeap, it works, I configured Maven to use snapshots repository, thanks.

**Comment by igorek9191** [comment]
One more question, could you explain to me, why in code of PersonController class (in jpa-example) such errors like on screenshot?  http://prntscr.com/hcwl6b
How I can start the application ?

**Comment by gslowikowski** [comment]
Check if you followed point **2. Configure project after import** from the [documentation](https://play2-maven-plugin.github.io/play2-maven-plugin/1.0.0-rc1/ide-integration-idea.html)
