### ISSUE TITLE
Incremental compilation (hot reload) support

### ISSUE THREAD

**Issue by tenstriker** [play2-maven-plugin/play2-maven-plugin#160]
This may not be an issue but more like a setup issue with Scala IDE. I did follow this doc : https://github.com/play2-maven-plugin/play2-maven-plugin/blob/master/src/site/markdown/ide-integration-eclipse.md

But it is not working . I need to rebuild pretty much everytime when I have a code change. I am running running play project from eclipse ide using Run Configuration as `play2:run -P eclipse`  
Its play-maven-scala project.

I see that in original sbt plugin incremental updates (hot reloads) is  supported via zinc. zinc can also be used externally. e.g. it's used by davidB's scala-maven-plugin. Is that something that can be supported via play2-maven-plugin as well for incremental updates?

**Comment by gslowikowski** [comment]
Hi @tenstriker 

Play! hot reload functionality in SBT and in Maven plugin is different from Zinc recompilation.

I would like to propose different approach:
- run `mvn play2:run` from the console, not from Scala IDE,
- open your application in the browser,
- work on the code in the IDE

Check (in Maven console) if Maven recompiles your app too often or not. I always use this approach.

In case of further problems, please:
- run `mvn play2:run -X > run.log 2>&1`
- open your application in the browser,
- work on the code in the IDE
- compress and attach here `run.log` file

**Comment by tenstriker** [comment]
Thanks for the alternate soln. I found that both in case of running from eclipse or command line that `jnotify` triggers file modification event and cause recompilation. It just eclipse hot code replace thinks it couldn't do it and gives me option to either continue, restart or terminate. I think that's because of different classloaders used by eclipse and play2-maven and they don't have any connector between them to communicate. If I just 'continue' upon getting that eclipse error of "Hot Code Replace Failed" it still works. I used to Terminate all the time before.

**Comment by gslowikowski** [comment]
Did you try running `play2:run` from the console, while working in the IDE?

**Comment by tenstriker** [comment]
I have tried `play2:run` from CLI but I find running it from Eclipse easier then starting JDT/Scala remote debugger. In my experience remote debugger crashes/goes out of synch more often then embedded one.

**Comment by gslowikowski** [comment]
Can we close this issue?
