### ISSUE TITLE
Scala IDE - Importing play maven project doesn't seem to recognize it as a jvm project

### ISSUE THREAD

**Issue by tenstriker** [play2-maven-plugin/play2-maven-plugin#175]
This might be scala ide bug more then this plugin. 
I don't see any build path created. No java or scala library gets automatically on build path. Only work around is to remove maven nature, remove my pom file, add maven nature, copy back my original pom file. Let me know if I should report this to scala ide forum instead. Thanks

**Comment by gslowikowski** [comment]
Hi @tenstriker 

I described problems with Eclipse in [documentation](https://play2-maven-plugin.github.io/play2-maven-plugin/1.0.0-rc2/ide-integration-eclipse.html).

Recently I found, how this special `eclipse` profile (described in documentation) can be activated automatically. The whole Maven profile should look like:
```xml
    <profiles>
        <profile>
            <id>eclipse</id> <!-- for M2Eclipse only -->

            <activation>
                <property>
                    <name>m2e.version</name>
                </property>
            </activation>

            <build>
                <directory>${project.basedir}/target-eclipse</directory>

                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <skipMain>true</skipMain>
                            <skip>true</skip>
                            <source>1.8</source>
                            <target>1.8</target>
                        </configuration>
                        <executions>
                            <execution>
                                <id>default-compile</id>
                                <goals><goal>compile</goal></goals>
                            </execution>
                            <execution>
                                <id>default-testCompile</id>
                                <goals><goal>testCompile</goal></goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
```

I don't like this. It's way too verbose.

Ideal solution would be to write small Eclipse plugin, similar to [m2eclipse-scala](https://github.com/sonatype/m2eclipse-scala), which would activate Java and Scala natures based on `sbt-compiler-maven-plugin` existence in projects with `jar` packaging and unconditionally in projects with `play2` packaging.
