### ISSUE TITLE
Play only starts in Prod mode when using the play2:run goal

### ISSUE THREAD

**Issue by gslowikowski** [play2-maven-plugin/play2-maven-plugin#6]
Originally reported on Google Code with ID 6

```
[play] [info] play - Application started (Prod)
[play] [info] play - Listening for HTTP on /0:0:0:0:0:0:0:0%0:9000

Everything seems to be working well except for being able to run the application in
Dev mode. Is this possible without the Play SBT plugin?
```

Reported by `aps@enclarify.com` on 2013-10-08 08:57:46

**Comment by schmitch** [comment]
actually just in case you could grab a lot of stuff from here now:
https://github.com/lagom/lagom/commit/b420c138a70f11e4cb7c02085b21dfee73ab2796
Since it's basically a layer on top of play you just need to check what's play related and create the Mojo's for it.

**Comment by gslowikowski** [comment]
Thank you @schmitch. I have already implemented everything, need to clean the code, add documentation and release. I see, in Lagom, you extracted a lot of watching, reloading, etc. code from Play! Framework `run-support` module. That's what I did too :) Can I contact you directly to ask some detailed questions?

**Comment by schmitch** [comment]
I'm not sure if I can help much, but feel free to do so.
But maybe you can contact @jroper he is the big boss when it comes to the `run-support` stuff I guess.

**Comment by domdorn** [comment]
Is this already included in any released version? I'm trying out beta5 and receive
     [play] [error] p.a.l.c.CryptoConfigParser - The application secret has not been set, and we are in prod mode. Your application is not secure.
     [play] [error] p.a.l.c.CryptoConfigParser - To set the application secret, please read http://playframework.com/documentation/latest/ApplicationSecret

.. it looks like the play server doesn't find the application.conf file, because I've changed the value of play.crypto.secret and it still fails to startup ..

**Comment by gslowikowski** [comment]
It will be in beta6, I hope by the end of this year.

What is your Play version? `play.crypto.secret` is proper key name for Play 2.4+. Earlier it was `application.secret`.

**Comment by domdorn** [comment]
I'm on 2.5 ... the samples in 
https://github.com/play2-maven-plugin/play2-maven-test-projects/tree/test-projects-1.0.0-beta5/play25/java/play-java-intro
 don't run.. meaning 

mvn play2:run
does not work because of this, even when manually changing the secret in conf/application.conf

**Comment by gslowikowski** [comment]
You changed the secret in `conf/application.conf` and didn't rebuild (`mvn process-classes`) afterwards.
`application.conf` is loaded from `target/classes` directory, not from `conf`. Instead of rebuilding, you can just copy this file to `target/classes`.
This will change when I release version with real run with hot-reload functionality.

**Comment by domdorn** [comment]
Thanks, that works!

**Comment by gslowikowski** [comment]
New `1.0.0-beta6-SNAPSHOT` snapshot deployed.

[Documentation](https://play2-maven-plugin.github.io/play2-maven-plugin/1.0.0-beta6-SNAPSHOT/index.html) updated. It will be improved. For now please read:
- [running in dev mode](https://play2-maven-plugin.github.io/play2-maven-plugin/1.0.0-beta6-SNAPSHOT/running.html) page,
- [run mojo parameters](https://play2-maven-plugin.github.io/play2-maven-plugin/1.0.0-beta6-SNAPSHOT/play2-maven-plugin/run-mojo.html) page.
